name: polpars
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz
  - astropy
  - corner
  - h5py
  - ipython
  - jupyterlab
  - lalsuite
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.8
  - scipy
  - seaborn
  - numexpr
  - parse
  - dask
  - imageio
  - pyspherical
